FROM golang:1.8.4-stretch as builder
WORKDIR /go/src/github.com/reubenmiller/smtpd/
RUN go get -d -v github.com/reubenmiller/smtpd
COPY smtp .


FROM mongo:3.0.15
WORKDIR /root/
RUN --from=builder /go/src/github.com/reubenmiller/smtpd/smtpd .
WORKDIR /mongodb
CMD ["smtpd"]
