version: '3'
services:
  web:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy: on-failure

    build: .
    ports:
      - "10025:10025"
      - "25000:25000"
      - "27017:27017"
